<?php
/**
 * Webino (https://github.com/webino/)
 *
 * @link      https://github.com/webino/WebinoImageThumb/ for the canonical source repository
 * @copyright Copyright (c) 2012-2014 Webino, s. r. o. (http://webino.sk/)
 * @license   BSD-3-Clause
 */

namespace WebinoImageThumb;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-12-04 at 14:22:09.
 */
class ModuleTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Module
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Module;
    }

    /**
     * @covers WebinoImageThumb\Module::getConfig
     */
    public function testGetConfig()
    {
        $config = $this->object->getConfig();
        $this->assertTrue(is_array($config));
    }

    /**
     * @covers WebinoImageThumb\Module::getAutoloaderConfig
     */
    public function testGetAutoloaderConfig()
    {
        $config = $this->object->getAutoloaderConfig();
        $this->assertTrue(is_array($config));
    }
}
