<?php
/**
 * Webino (https://github.com/webino/)
 *
 * @link      https://github.com/webino/WebinoImageThumb/ for the canonical source repository
 * @copyright Copyright (c) 2012-2014 Webino, s. r. o. (http://webino.sk/)
 * @license   BSD-3-Clause
 */

namespace WebinoImageThumb;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-07-12 at 14:11:34.
 */
class WebinoImageThumbTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var WebinoImageThumb
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new WebinoImageThumb;
    }

    /**
     * @covers WebinoImageThumb\WebinoImageThumb::create
     */
    public function testCreate()
    {
        $src   = __DIR__ . '/../resources/test.jpg';
        $thumb = $this->object->create($src);
        $this->assertInstanceOf('PHPThumb\GD', $thumb);
    }

    /**
     * @covers WebinoImageThumb\WebinoImageThumb::create
     */
    public function testCreateMissing()
    {
        $this->setExpectedException('WebinoImageThumb\Exception\RuntimeException');
        $src = __DIR__ . '/../resources/this_should_not_exist.jpg';
        $this->object->create($src);
    }

    /**
     * @covers WebinoImageThumb\WebinoImageThumb::createReflection
     */
    public function testCreateReflection()
    {
        $plugin = $this->object->createReflection(50, 50, 50, true, '#505050');
        $this->assertInstanceOf('PHPThumb\Plugins\Reflection', $plugin);
    }

    /**
     * @covers WebinoImageThumb\WebinoImageThumb::createWhiteSpaceCropper
     */
    public function testCreateWhiteSpaceCropper()
    {
        $plugin = $this->object->createWhiteSpaceCropper();
        $this->assertInstanceOf('WebinoImageThumb\PHPThumb\Plugin\WhiteSpaceCropper', $plugin);
    }

    /**
     * @covers WebinoImageThumb\WebinoImageThumb::createSharpen
     */
    public function testCreateSharpen()
    {
        $plugin = $this->object->createSharpen();
        $this->assertInstanceOf('WebinoImageThumb\PHPThumb\Plugin\Sharpen', $plugin);
    }
}
