<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'WebinoImageThumb\WebinoImageThumb'             => __DIR__ . '/src/WebinoImageThumb/WebinoImageThumb.php',
    'WebinoImageThumb\Module'                       => __DIR__ . '/src/WebinoImageThumb/Module.php',
    'WebinoImageThumb\Exception\ExceptionInterface' => __DIR__ . '/src/WebinoImageThumb/Exception/ExceptionInterface.php',
    'WebinoImageThumb\Exception\RuntimeException'   => __DIR__ . '/src/WebinoImageThumb/Exception/RuntimeException.php',
);
