<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'ThumbBase'       => __DIR__ . '/src/PHPThumb/ThumbBase.inc.php',
    'PhpThumbFactory' => __DIR__ . '/src/PHPThumb/ThumbLib.inc.php',
    'GdThumb'         => __DIR__ . '/src/PHPThumb/GdThumb.inc.php',
    'GdReflectionLib' => __DIR__ . '/src/PHPThumb/thumb_plugins/gd_reflection.inc.php',
    'PhpThumb'        => __DIR__ . '/src/PHPThumb/PhpThumb.inc.php',
);