<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'WebinoImageThumb\WebinoImageThumb'             => __DIR__ . '/WebinoImageThumb.php',
  'WebinoImageThumb\Module'                       => __DIR__ . '/Module.php',
  'WebinoImageThumb\Exception\ExceptionInterface' => __DIR__ . '/Exception/ExceptionInterface.php',
  'WebinoImageThumb\Exception\RuntimeException'   => __DIR__ . '/Exception/RuntimeException.php',
);
