<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'WebinoImageThumb\Exception\ExceptionInterface'      => __DIR__ . '/Exception/ExceptionInterface.php',
  'WebinoImageThumb\Exception\RuntimeException'        => __DIR__ . '/Exception/RuntimeException.php',
  'WebinoImageThumb\Module'                            => __DIR__ . '/Module.php',
  'WebinoImageThumb\PhpThumb\Plugin\Sharpen'           => __DIR__ . '/PhpThumb/Plugin/Sharpen.php',
  'WebinoImageThumb\PhpThumb\Plugin\WhitespaceCropper' => __DIR__ . '/PhpThumb/Plugin/WhitespaceCropper.php',
  'WebinoImageThumb\WebinoImageThumb'                  => __DIR__ . '/WebinoImageThumb.php',
);
